include ../../flow/Makefile.flow

#LIB_H 	:= inc/
#IDIR 	:= -I$(LIB_H)
#SRC 	:= $(wildcard src/*.cpp)
#BNC_SRC	= $(SRC:src/%.cpp=%)
#OBJS   = $(BNC_SRC:%=$(PROJ_PATH)obj/%.o)

#build: output $(OBJS)
		
#output: clean
#	@echo "Compiling: $(BNC_SRC)"	

#$(PROJ_PATH)obj/%.o : src/%.cpp
#	@mkdir -p $(dir $@)§""
#	$(CC) -c $(CFLAGS) $(IDIR) -o $@ $<

#clean:
#	@rm -f $(OBJS)

